export CC=gcc
export CFLAGS=-Wall -std=c99 -pedantic -g
export LDFLAGS=

export OBJ= $

FSLIO_DIR=fslio
NIFTIIO_DIR=niftiio
ZNZLIB_DIR=znzlib

EXEC=bcbnifti

all:$(EXEC)
	(cd $FSLIO_DIR

main : main.o
	$(CC) $(CFLAGS) -o $@ $^

main.o : main.c
	$(CC) $(CFLAGS) -o $@ -c $<

bcbnifti : bcbnifti.o
	$(CC) $(CFLAGS) -o $@ $^

bcbnifti.o : bcbnifti.c bcbnifti.h
	$(CC) $(CFLAGS) -o $@ -c $<

clean :
	$(RM) -rf *.o

mrproper : clean
	$(RM) -rf $(EXEC)
